import { Heading, Text, VStack, UnorderedList, ListItem, Link as ChakraLink } from '@chakra-ui/react';
import { useConfig } from '../../hooks/useConfig';
import { FC } from 'react';

export const TermsOfService: FC = () => {
  const effectiveDate = 'April 25, 2025';
  const { appName: companyName, supportEmail } = useConfig();

  return (
    <VStack spacing={6} align="stretch">
      <Text>Effective Date: {effectiveDate}</Text>

      <Heading as="h3" size="md">
        1. Acceptance of Terms
      </Heading>
      <Text>
        Welcome to {companyName}! These Terms of Service ("Terms") govern your access to and use of the {companyName}
        website, application, APIs, and services (collectively, the "Service"). By accessing or using the Service, you
        agree to be bound by these Terms. If you do not agree to these Terms, do not use the Service.
      </Text>

      <Heading as="h3" size="md">
        2. Description of Service
      </Heading>
      <Text>
        {companyName} provides an AI-powered chat service that synthesizes information from various sources to answer
        user queries. The Service includes user authentication, real-time interaction, and access via web interfaces and
        APIs. Features and capabilities may change over time.
      </Text>

      <Heading as="h3" size="md">
        3. User Accounts
      </Heading>
      <Text>
        You may need to register for an account to access certain features. You agree to provide accurate and complete
        information during registration and keep your account information updated. You are responsible for maintaining
        the confidentiality of your account credentials and for all activities that occur under your account. You must
        notify us immediately of any unauthorized use of your account.
      </Text>

      <Heading as="h3" size="md">
        4. User Conduct and Responsibilities
      </Heading>
      <Text>You agree not to use the Service:</Text>
      <UnorderedList spacing={1} pl={5}>
        <ListItem>For any illegal or unauthorized purpose.</ListItem>
        <ListItem>To harass, abuse, defame, or harm others.</ListItem>
        <ListItem>To transmit viruses, malware, or other malicious code.</ListItem>
        <ListItem>To infringe upon the intellectual property rights of others.</ListItem>
        <ListItem>To attempt to gain unauthorized access to the Service or related systems.</ListItem>
        <ListItem>To generate content that is hateful, discriminatory, or violates applicable laws.</ListItem>
        <ListItem>In any way that could damage, disable, overburden, or impair the Service.</ListItem>
      </UnorderedList>
      <Text>
        You are solely responsible for the content you submit or generate through the Service ("User Content") and for
        ensuring it complies with these Terms and applicable laws.
      </Text>

      <Heading as="h3" size="md">
        5. Intellectual Property
      </Heading>
      <Text>
        The Service and its original content (excluding User Content generated by you), features, and functionality are
        and will remain the exclusive property of {companyName} and its licensors. The Service is protected by
        copyright, trademark, and other laws. Our trademarks may not be used in connection with any product or service
        without our prior written consent. You retain ownership of your original User Content, but you grant
        {companyName} a worldwide, non-exclusive, royalty-free license to use, reproduce, modify, and display such
        content solely for the purpose of operating and improving the Service.
      </Text>

      <Heading as="h3" size="md">
        6. Disclaimers
      </Heading>
      <Text>
        The Service is provided on an "AS IS" and "AS AVAILABLE" basis. {companyName} makes no warranties, express or
        implied, regarding the accuracy, reliability, or completeness of the information provided by the AI or the
        availability or security of the Service. Use of the Service is at your own risk. We do not warrant that the
        Service will meet your requirements or be uninterrupted, error-free, or free of harmful components. AI-generated
        content may contain inaccuracies or errors; do not rely on it for critical decisions without verification.
      </Text>

      <Heading as="h3" size="md">
        7. Limitation of Liability
      </Heading>
      <Text>
        To the maximum extent permitted by applicable law, {companyName}, its affiliates, directors, employees, agents,
        and licensors shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or
        any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or
        other intangible losses, resulting from (a) your access to or use of or inability to access or use the Service;
        (b) any conduct or content of any third party on the Service; (c) any content obtained from the Service; or (d)
        unauthorized access, use, or alteration of your transmissions or content.
      </Text>

      <Heading as="h3" size="md">
        8. Termination
      </Heading>
      <Text>
        We may terminate or suspend your access to the Service immediately, without prior notice or liability, for any
        reason whatsoever, including without limitation if you breach these Terms. Upon termination, your right to use
        the Service will cease immediately. You may terminate your account at any time by using the account deletion
        feature within the Service or by contacting us.
      </Text>

      <Heading as="h3" size="md">
        9. Governing Law
      </Heading>
      <Text>
        These Terms shall be governed and construed in accordance with the laws of Republic of Bulgaria, without regard
        to its conflict of law provisions.
      </Text>

      <Heading as="h3" size="md">
        10. Changes to Terms
      </Heading>
      <Text>
        We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is
        material, we will provide reasonable notice prior to any new terms taking effect. What constitutes a material
        change will be determined at our sole discretion. By continuing to access or use our Service after any revisions
        become effective, you agree to be bound by the revised terms.
      </Text>

      <Heading as="h3" size="md">
        11. Contact Us
      </Heading>
      <Text>
        If you have any questions about these Terms, please contact us at:{' '}
        <ChakraLink href={`mailto:${supportEmail}`} isExternal color="teal.500">
          {supportEmail}
        </ChakraLink>
      </Text>
    </VStack>
  );
};
